export type AllowedAttribute = Record<string, 1 | 0>
export type AllowedTags = Record<string, AllowedAttribute>
export type AllowedProtocols = string[]

const ariaProps: AllowedAttribute = {
  'aria-controls': 1,
  'aria-current': 1,
  'aria-describedby': 1,
  'aria-details': 1,
  'aria-expanded': 1,
  'aria-hidden': 1,
  'aria-label': 1,
  'aria-labelledby': 1,
  'aria-live': 1,
}

const commonProps: AllowedAttribute = {
  ...ariaProps,
  class: 1,
  'data-*': 1,
  dir: 1,
  hidden: 1,
  id: 1,
  lang: 1,
  style: 1,
  title: 1,
  role: 1,
  'xml:lang': 1,
}

export const allowedPostProtocols: AllowedProtocols = ['http', 'https']
export const allowedPostTags: AllowedTags = {
  address: { ...commonProps },
  a: {
    href: 1,
    rel: 1,
    rev: 1,
    name: 1,
    target: 1,
    download: 1,
    ...commonProps,
  },
  abbr: { ...commonProps },
  acronym: { ...commonProps },
  area: {
    alt: 1,
    coords: 1,
    href: 1,
    nohref: 1,
    shape: 1,
    target: 1,
    ...commonProps,
  },
  article: {
    align: 1,
    ...commonProps,
  },
  aside: {
    align: 1,
    ...commonProps,
  },
  audio: {
    autoplay: 1,
    controls: 1,
    loop: 1,
    muted: 1,
    preload: 1,
    src: 1,
    ...commonProps,
  },
  b: { ...commonProps },
  bdo: { ...commonProps },
  big: { ...commonProps },
  blockquote: {
    cite: 1,
    ...commonProps,
  },
  br: { ...commonProps },
  button: {
    disabled: 1,
    name: 1,
    type: 1,
    value: 1,
    ...commonProps,
  },
  caption: {
    align: 1,
    ...commonProps,
  },
  cite: { ...commonProps },
  code: { ...commonProps },
  col: {
    align: 1,
    char: 1,
    charoff: 1,
    span: 1,
    valign: 1,
    width: 1,
    ...commonProps,
  },
  colgroup: {
    align: 1,
    char: 1,
    charoff: 1,
    span: 1,
    valign: 1,
    width: 1,
    ...commonProps,
  },
  del: {
    datetime: 1,
    ...commonProps,
  },
  dd: { ...commonProps },
  dfn: { ...commonProps },
  details: {
    align: 1,
    open: 1,
    ...commonProps,
  },
  div: {
    align: 1,
    ...commonProps,
  },
  dl: { ...commonProps },
  dt: { ...commonProps },
  em: { ...commonProps },
  fieldset: { ...commonProps },
  figure: {
    align: 1,
    ...commonProps,
  },
  figcaption: {
    align: 1,
    ...commonProps,
  },
  font: {
    color: 1,
    face: 1,
    size: 1,
    ...commonProps,
  },
  footer: {
    align: 1,
    ...commonProps,
  },
  h1: {
    align: 1,
    ...commonProps,
  },
  h2: {
    align: 1,
    ...commonProps,
  },
  h3: {
    align: 1,
    ...commonProps,
  },
  h4: {
    align: 1,
    ...commonProps,
  },
  h5: {
    align: 1,
    ...commonProps,
  },
  h6: {
    align: 1,
    ...commonProps,
  },
  header: {
    align: 1,
    ...commonProps,
  },
  hgroup: {
    align: 1,
    ...commonProps,
  },
  hr: {
    align: 1,
    noshade: 1,
    size: 1,
    width: 1,
    ...commonProps,
  },
  i: { ...commonProps },
  img: {
    alt: 1,
    align: 1,
    border: 1,
    height: 1,
    hspace: 1,
    loading: 1,
    longdesc: 1,
    vspace: 1,
    src: 1,
    usemap: 1,
    width: 1,
    ...commonProps,
  },
  ins: {
    datetime: 1,
    cite: 1,
    ...commonProps,
  },
  kbd: { ...commonProps },
  label: {
    for: 1,
    ...commonProps,
  },
  legend: {
    align: 1,
    ...commonProps,
  },
  li: {
    align: 1,
    value: 1,
    ...commonProps,
  },
  main: {
    align: 1,
    ...commonProps,
  },
  map: {
    name: 1,
    ...commonProps,
  },
  mark: { ...commonProps },
  menu: {
    type: 1,
    ...commonProps,
  },
  nav: {
    align: 1,
    ...commonProps,
  },
  object: {
    data: 1,
    type: 1,
    ...commonProps,
  },
  p: {
    align: 1,
    ...commonProps,
  },
  pre: {
    width: 1,
    ...commonProps,
  },
  q: {
    cite: 1,
    ...commonProps,
  },
  rb: { ...commonProps },
  rp: { ...commonProps },
  rt: { ...commonProps },
  rtc: { ...commonProps },
  ruby: { ...commonProps },
  s: { ...commonProps },
  samp: { ...commonProps },
  span: {
    align: 1,
    ...commonProps,
  },
  section: {
    align: 1,
    ...commonProps,
  },
  small: { ...commonProps },
  strike: { ...commonProps },
  strong: { ...commonProps },
  sub: { ...commonProps },
  summary: {
    align: 1,
    ...commonProps,
  },
  sup: { ...commonProps },
  table: {
    align: 1,
    bgcolor: 1,
    border: 1,
    cellpadding: 1,
    cellspacing: 1,
    rules: 1,
    summary: 1,
    width: 1,
    ...commonProps,
  },
  tbody: {
    align: 1,
    char: 1,
    charoff: 1,
    valign: 1,
    ...commonProps,
  },
  td: {
    abbr: 1,
    align: 1,
    axis: 1,
    bgcolor: 1,
    char: 1,
    charoff: 1,
    colspan: 1,
    headers: 1,
    height: 1,
    nowrap: 1,
    rowspan: 1,
    scope: 1,
    valign: 1,
    width: 1,
    ...commonProps,
  },
  textarea: {
    cols: 1,
    rows: 1,
    disabled: 1,
    name: 1,
    readonly: 1,
    ...commonProps,
  },
  tfoot: {
    align: 1,
    char: 1,
    charoff: 1,
    valign: 1,
    ...commonProps,
  },
  th: {
    abbr: 1,
    align: 1,
    axis: 1,
    bgcolor: 1,
    char: 1,
    charoff: 1,
    colspan: 1,
    headers: 1,
    height: 1,
    nowrap: 1,
    rowspan: 1,
    scope: 1,
    valign: 1,
    width: 1,
    ...commonProps,
  },
  thead: {
    align: 1,
    char: 1,
    charoff: 1,
    valign: 1,
    ...commonProps,
  },
  title: { ...commonProps },
  tr: {
    align: 1,
    bgcolor: 1,
    char: 1,
    charoff: 1,
    valign: 1,
    ...commonProps,
  },
  track: {
    default: 1,
    kind: 1,
    label: 1,
    src: 1,
    srclang: 1,
    ...commonProps,
  },
  tt: { ...commonProps },
  u: { ...commonProps },
  ul: {
    type: 1,
    ...commonProps,
  },
  ol: {
    start: 1,
    type: 1,
    reversed: 1,
    ...commonProps,
  },
  var: { ...commonProps },
  video: {
    autoplay: 1,
    controls: 1,
    height: 1,
    loop: 1,
    muted: 1,
    playsinline: 1,
    poster: 1,
    preload: 1,
    src: 1,
    width: 1,
    ...commonProps,
  },
  svg: {
    'aria-hidden': 1,
    class: 1,
    fill: 1,
    focusable: 1,
    height: 1,
    id: 1,
    role: 1,
    style: 1,
    viewbox: 1,
    width: 1,
    xmlns: 1,
  },
  animatetransform: {
    attributename: 1,
    begin: 1,
    calcmode: 1,
    dur: 1,
    fill: 1,
    keysplines: 1,
    repeatcount: 1,
    values: 1,
  },
  g: {
    'clip-path': 1,
    fill: 1,
    'fill-rule': 1,
    style: 1,
    transform: 1,
  },
  line: {
    id: 1,
    x1: 1,
    y1: 1,
    x2: 1,
    y2: 1,
  },
  path: {
    class: 1,
    d: 1,
    fill: 1,
    'fill-opacity': 1,
    id: 1,
    stroke: 1,
    'stroke-linecap': 1,
    'stroke-linejoin': 1,
    'stroke-width': 1,
    style: 1,
    transform: 1,
  },
  polyline: {
    id: 1,
    points: 1,
  },
  rect: {
    'clip-path': 1,
    fill: 1,
    height: 1,
    style: 1,
    rx: 1,
    transform: 1,
    width: 1,
    x: 1,
    y: 1,
  },
  use: {
    href: 1,
    'xlink:href': 1,
  },
}
